name: build-macos-x86_64
run-name: Building All in Anki for Anki ${{ inputs.version }} on MacOS x86_64

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: Anki release version
        required: true

jobs:
  build-package:
    runs-on: macos-13
    env:
      output_name: "allinanki-${{ inputs.version }}-macos-x86_64"
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"
          cache: "pip"
      - name: "Install prerequisities"
        run: python -m pip install -r requirements.txt anki-release==${{ inputs.version }}
      - name: "Patch aqt module"
        run: python patches/patch_aqt.py
      - name: "Build package"
        run: pyinstaller --onedir --hidden-import anki --hidden-import aqt --collect-all _aqt --collect-all anki_mac_helper --collect-all anki_audio --argv-emulation --noconfirm --noconsole --icon resources/anki.icns --name Anki allinanki.py
      - name: "Patch Info.plist"
        run: python patches/patch_plist.py
      - name: "Include extra files"
        run: |
          cp README.md LICENSE dist/Anki.app
      - name: "Compress output"
        run: |
          tar -czf dist/${{ env.output_name }}.tar.gz -C dist/ Anki.app/
          shasum -a 256 dist/${{ env.output_name }}.tar.gz
      - name: "Upload artifact"
        uses: actions/upload-artifact@v5
        with:
          name: "${{ env.output_name }}"
          path: "dist/${{ env.output_name }}.tar.gz"
          compression-level: 0
          if-no-files-found: error
